### ISSUE TITLE
Improve the description of application on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.jitsi.jitsi-meet#1]
Hi.
1st of all, I would like to say thank you too much for making this cute video conference program available as flatpak on FlatHub ! It came at exact time before beginning of new Academic years, which unfortunately mostly will associated with continue COVID19 attack ...

I tested the application & it run very well without error ...

Only concern is that I notice - during your PR - that you asked to copy from description of Android application on Google play .... This is okay because really description on jitsi-meet-electron repository on GitHub is too short. However, there are 2 points in this "too" short description that are very needed to be added for that from Android version. These 2 points are:

- End-to-End Encryption support (BETA).
- Support for deeplinks such as jitsi-meet://myroom (will open myroom on the configured Jitsi instance) or jitsi-meet://jitsi.mycompany.com/myroom (will open myroom on the Jitsi instance running on jitsi.mycompany.com).

Specially 1st & last one are very important to be added ...
Regarding the line "End-to-End Encryption support (BETA)." should added bellow the current line "Encrypted by default.", while the point "Support for deeplinks such ........." should come at last to be bellow the related current line "Invite by pretty URLs: ........."

Also, there are other lines, you can add them, which are:
- Works with any Jitsi Meet deployment.
- Remote control.
- Always-On-Top window.
But these are not so important as the 1st two that I open this issue specially for them.

Thank you again for your kind efforts !

**Comment by haggen88** [comment]
https://flathub.org/apps/details/org.jitsi.jitsi-meet
Thank you so much !

**Comment by ananace** [comment]
Just pushed an update to the description - b056362, albeit with a slightly different wording.
Also fixed the jitsi-meet:// URL handling while I was at it.
