### ISSUE TITLE
Ability to run with Wayland and PipeWire

### ISSUE THREAD

**Issue by daenney** [flathub/org.jitsi.jitsi-meet#17]
As of 2.8.4, Jitsi uses Electron 12 which can be ran with `--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland`. However, this doesn't work for the Flatpak right now.

I suspect that's mostly because it uses `--socket=X11` and could probably be fixed by adding a `--socket=wayland`. I'm not sure if anything else needs doing to enable Pipewire

**Comment by ananace** [comment]
I added the `--socket=wayland` finish arg, haven't actually got a system to test it with but the build seemed to work on my laptop, could you check if that's enough to get it working fully with wayland?

**Comment by daenney** [comment]
I think we're halfway there! It starts with Wayland now (the window decorations go missing so that's how I know :smile:) but PipeWire doesn't work yet:

```
[10:0413/105133.913722:ERROR:base_capturer_pipewire.cc(522)] Failed to load the PipeWire library and symbols.
[10:0413/105151.563019:ERROR:base_capturer_pipewire.cc(522)] Failed to load the PipeWire library and symbols.
```

Chromium/Electron needs libpipewire02 for this. It's installed on my host, but I suppose that's not available to the pak. I tried with `flatpak override --filesystem=xdg-run/pipewire-0:ro org.jitsi.jitsi-meet` but Chromium still needs libpipewire02 which I'm guessing is causing problems.

I don't really know enough about Flatpak to figure out how to fix that last one.

**Comment by ananace** [comment]
Well, threw in PipeWire 0.2.7 as well, no idea how the interop will do, but it should be there at least.

**Comment by daenney** [comment]
Works now :100:

**Comment by ananace** [comment]
Good to hear, I'll be closing this issue then.

**Comment by vchernin** [comment]
Running with pipewire _by default_ was [is now fixed upstream](https://github.com/jitsi/jitsi-meet-electron/pull/584). This means that manually running the flatpak with PipeWire may not be necessary. Right now you need to run `flatpak run org.jitsi.jitsi-meet --enable-features=WebRTCPipeWireCapturer` to get PipeWire working.

In case the upstream fix doesn't affect the flatpak we could also just add the flag to the flatpak desktop file as [done here](https://github.com/flathub/com.slack.Slack/pull/118/commits/8552181dc907f00b9682c784c8876205098d3617).
