### ISSUE TITLE
No microphone permissions Devuan Beowulf

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/org.jitsi.jitsi-meet#2]
Even when the privileges (flatpak level) are given by default for accessing devices, the app is not requesting permission for such devices inside (electron/webapp level) or are not given by default.

I cannot speak because of that.

I am currently using Devuan Beowulf (Debian Buster).

**Comment by ananace** [comment]
I'm unable to verify this on any of the computers I have access to at the moment, even on my old Gentoo laptop with Flatpak 1.4.0 I'm getting both camera and mic/speaker working just fine with just an install and launch.
What versions do you have of Flatpak? Pulse? V4L?

**Comment by EchedeyLR** [comment]
The lasts of Debian Buster. This is why I gave distro version.

**Comment by EchedeyLR** [comment]
Flatpak: 1.2.5
PulseAudio: 12.2
V4L: 1.16.3

**Comment by ananace** [comment]
Thanks, I was able to spin up a VM with a Debian Buster live image and those versions.  
With my USB headset and webcam passed through into the VM I still can't replicate the issue, audio/video both work just fine in there, and I was able to participate in a test call against my laptop without changing a single setting.

**Comment by EchedeyLR** [comment]
Could you test on Devuan Beowulf?

**Comment by EchedeyLR** [comment]
I tried Element from flatpak too but seems that has the same issue. This doesn't happen on Chromium nor Audacity but from Devuan repos, not flatpak.

**Comment by ananace** [comment]
Grabbed a Devuan Beowulf image as well, bumped the RAM slightly to get that to work in a live environment, passed through my webcam and headset, and I am still not able to replicate your issue.
With Devuan running Jitsi still managed to grab both audio and video without issue, I was able to join a call with my laptop and both send and receive.

**Comment by EchedeyLR** [comment]
Then I don't understand, this is just Devuan Beowulf with Mate and flatpak. Are you sure you used Devuan Beowulf with Mate?

I make special dedication to Mate because I wanted to ensure if was an issue on the tasksel not installing some package that should be.

**Comment by EchedeyLR** [comment]
Which more info should I give?

**Comment by EchedeyLR** [comment]
I have news. 

I changed main description because I recognize that I added camera when I was not testing that part, the issues is centered with the microphone (sorry for that, and a lot  I missed that part and wrote it in the description ;-;).

I connected an USB camera now and you know what?, it is detected, but the microphone remains undetected for some reason.

**Comment by EchedeyLR** [comment]
I discovered the specific issue. When Mate starts, it calls "start-pulseaudio-x11" to start pulseaudio service but seems that is not working so I started manually with "pulseaudio --start" and the microphone was suddenly detected.

As this is not a flatpak issue I close issue here or feel free to re-do it to avoid being opened again.
