### ISSUE TITLE
Filesystem permissions

### ISSUE THREAD

**Issue by dbrgn** [flathub/org.jitsi.jitsi-meet#20]
Right now I cannot pick any file as background image because the only filesystem access is `--filesystem=xdg-run/pipewire-0`.

I can override the permissions with `sudo flatpak override org.jitsi.jitsi-meet --filesystem=home --filesystem=xdg-run/pipewire-0`, but isn't this an ideal case for a Portal? Does Electron support the Portal API?

**Comment by ananace** [comment]
The Electron support for the file-chooser portal was merged with https://github.com/electron/electron/pull/19159 - and seems to be slated for release with Electron 14.
