### ISSUE TITLE
Ship pre-releases?

### ISSUE THREAD

**Issue by vchernin** [flathub/org.jitsi.jitsi-meet#25]
I see in #23 2.8.8 was released to Flathub stable. [However 2.8.8 is a pre-release](https://github.com/jitsi/jitsi-meet-electron/releases).

Do we want to ship pre-releases to Flathub stable? Should x-checker-data be changed to not open PRs for pre-releases?

**Comment by ananace** [comment]
In this case it's a bit of a unique situation, 2.8.8 was a full release until after I'd personally tested it and accepted the updated release, at that point they "downgraded" the release to a pre-release state on GitHub.  
Which admittedly did result in a failure in the data checker, in that it attempted to add a 2.8.7 release _after_ the 2.8.8 one to get the flatpak back to a stable release.

I'm waiting to see a reason for the change from a full release to a pre-release before I choose to revert or not.

**Comment by ananace** [comment]
Well, 2.8.8 is a full and proper release again, so maybe it was just a mistake by one of the jitsi devs. I'm going to close this issue now.
