### ISSUE TITLE
Version 2.4.0 released

### ISSUE THREAD

**Issue by ovari** [flathub/org.jitsi.jitsi-meet#3]
https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2.4.0

Thank you

**Comment by ovari** [comment]
@ananace does flathub automatically update?

**Comment by ananace** [comment]
Just pushed an update to the new version, as soon as the automated builds finish then the new version will be up on Flathub.

**Comment by ovari** [comment]
Thanks for the update.

Can you please advise where we can translate into the hu (Hungarian - magyar) locale `Jitsi Meet Desktop App` --> `Jitsi Meet asztali alkalmazás`?
![image](https://user-images.githubusercontent.com/17465872/94322245-404b1200-ffd5-11ea-8057-7f1a46518810.png)

Thank you once again.

**Comment by ovari** [comment]
https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.desktop

**Comment by ovari** [comment]
https://github.com/flathub/org.jitsi.jitsi-meet/issues/4
