### ISSUE TITLE
Drop --filesystem=xdg-run/pipewire-0 from manifest

### ISSUE THREAD

**Issue by rmader** [flathub/org.jitsi.jitsi-meet#31]
The fact that screen sharing required Pipewire socked access despite using the xdg portal was a [WebRTC bug](https://webrtc-review.googlesource.com/c/src/+/230803). Once the fix has reached stable, `--filesystem=xdg-run/pipewire-0` can be dropped.

**Comment by ananace** [comment]
Going to have to wait for a Chromium release to be tagged with it, then for Electron to move to that version, and then for Jitsi to release a new version of their package built on the new Electron version. So probably going to be a while.

**Comment by WhyNotHugo** [comment]
Nice, thanks for updating this!
