### ISSUE TITLE
Screen share doesn't work anymore in KDE wayland and permission popup has endless loop

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.jitsi.jitsi-meet#39]
After latest update, on Fedora 35 KDE wayland session, when trying to screen share, I can't, and the screen share permission popup keeps duplicating in an endless loop.

Edit: Happens on AppImage version also.

**Comment by pizzadude** [comment]
https://github.com/jitsi/jitsi-meet-electron/issues/677

**Comment by pizzadude** [comment]
It happens in both the AppImage and the flatpak, for now I guess I'll downgrade the flatpak to a previous version, since the AppImage has auto update.

**Comment by lapor-kris** [comment]
It is the same with Gnome desktop on Fedora 35.

**Comment by joshua-stone** [comment]
I can also confirm that Jitsi Meet's screenshare option is broken on Fedora as it goes into an endless loop.

```
$ rpm -q flatpak gnome-shell xdg-desktop-portal
flatpak-1.12.2-1.fc35.x86_64
gnome-shell-41.2-1.fc35.x86_64
xdg-desktop-portal-1.10.1-2.fc35.x86_64
```

**Comment by pizzadude** [comment]
Seems to be fixed for me. Fedora 35 KDE Wayland. KDE 5.24.1, latest Jitsi Meet flatpak

Can anyone else confirm?

Full system info:

```
Operating System: Fedora Linux 35
KDE Plasma Version: 5.24.1
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.9-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

```
