### ISSUE TITLE
create `org.jitsi.jitsi-meet.desktop` file

### ISSUE THREAD

**Issue by ovari** [flathub/org.jitsi.jitsi-meet#4]
Please create a `desktop` file to enable Jitsi Meet properties to be translated.

For example, please see the Thunderbird `desktop` file:
https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.desktop

This would enable the string in red in the image below, as well as other strings, to be translated
![image](https://user-images.githubusercontent.com/17465872/94323068-bf414a00-ffd7-11ea-91bd-fd59d69f3303.png)

What do you think?

Thank you

**Comment by bilelmoussaoui** [comment]
You should contribute that translation upstream. But as it's an electron app, it's probably generated at build time.

**Comment by ovari** [comment]
Thunderbird Flatpak on Flathub is also done like suggested here, as shown at https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.desktop.

Unless we are missing something.

**Comment by ovari** [comment]
@saghul can the `org.jitsi.jitsi-meet.desktop` file be added upstream? Thank you

**Comment by ovari** [comment]
@ananace can the `org.jitsi.jitsi-meet.desktop` file be added here? Thank you

**Comment by saghul** [comment]
I'd take a patch sure.

**Comment by bilelmoussaoui** [comment]
As the app uses electron-builder the file is generated from the following attributes https://github.com/jitsi/jitsi-meet-electron/blob/master/package.json#L42-L46, i wonder if there's an attribute that makes it uses a file instead.

**Comment by ananace** [comment]
I'd love to see these things pushed upstream if possible, to keep the amount of Flatpak-specific work down, especially as it's work that non-Flatpak builds would have just as much use of.

**Comment by ovari** [comment]
### File location

Where should the file be located?

* https://github.com/ovari/jitsi-meet-electron/org.jitsi.jitsi-meet.desktop
* https://github.com/ovari/jitsi-meet-electron/resources/org.jitsi.jitsi-meet.desktop
* https://github.com/ovari/jitsi-meet-electron/app/org.jitsi.jitsi-meet.desktop

Somewhere else?

### Properties

From https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.desktop, how should the following change?
```
Version=1.0
Encoding=UTF-8
Exec=thunderbird %u
Icon=thunderbird
Terminal=false
Type=Application
MimeType=message/rfc822;x-scheme-handler/mailto;
StartupNotify=false
Categories=Network;Email;
```

Thank you

**Comment by ananace** [comment]
As their current desktop file is generated by electron-builder, the best way to do that would probably be to still use whatever methods that allows. Though if you wish to do it with a loose desktop file, upstream would still be the best place to ask where they'd like such a file.

From having a quick look at [the electron-build docs](https://www.electron.build/configuration/linux) my guess is that for your wished changes, you'd want to edit [the upstream package.json](https://github.com/jitsi/jitsi-meet-electron/blob/master/package.json#L42-L46) with something like;
```javascript
"linux": {
  /* ... */

  "desktop": {
    "Name[en]": "Jitsi Meet Desktop App",
    "Name[de]": "Jitsi Meet Desktop App - but in German.",
    /* etc */
  },

  /* ... */
}
```

**Comment by ovari** [comment]
Do you know how to access debug logs using the web-based interface? For example
`C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2020-09-27T08_07_19_787Z-debug.log`

**Comment by csett86** [comment]
Upstream here, since yesterdays version we have 10 translations in the upstream desktop source: https://github.com/jitsi/jitsi-meet-electron/blob/master/package.json#L64-L75

Thus I would consider this closed. Happy to take any further translations as PRs upstream as well.
