### ISSUE TITLE
Option to disable the (annoying) window that pops up when Meet loses focus

### ISSUE THREAD

**Issue by axelsimon** [flathub/org.jitsi.jitsi-meet#61]
This should be an option that can be configured. It might not be specific to the Flatpak, but i'm using the Flatpak so reporting here :)

**Comment by csett86** [comment]
Its already there, before joining a conference, go into the settings of the app via the gear icon on the left and disable the "Always on Top Window"

**Comment by axelsimon** [comment]
Thanks, i had no idea that was there! Closing this issue then :slightly_smiling_face:
