### ISSUE TITLE
Cannot share screen on Fedora 33

### ISSUE THREAD

**Issue by lapor-kris** [flathub/org.jitsi.jitsi-meet#7]
I installed Meet Jisti from Flathub, but I cannot share screen. I use Fedora 33 and Wayland. Is this a Fedora issue or Flatpak version of Jitsi Meet, of Flatpak in general?
Thanks

**Comment by ananace** [comment]
I'm not up to date on Fedora, are you on Wayland or X?

I don't think screen share on Wayland is working yet for Electron apps - it's broken for at least Discord and MS Teams, so if that's the case then it's likely that's the issue.

**Comment by lapor-kris** [comment]
I am on Wayland. I also got this post from Jordan Petridis: "That's kinda expected, the required patches fedora ships are not yet fully merged upstream."
So I guess Fedora has to merge patches to upstream. I think we can close this issue, as it's not part of the flatpak version of Meet.
