### ISSUE TITLE
Jitsi Meet for ARM

### ISSUE THREAD

**Issue by sallyahaj** [flathub/org.jitsi.jitsi-meet#73]
Hello there!,
Is there a plan to add aarch64 support? I think that would be very handy, especially as the ARM CPU started to spread.
Thank you.

**Comment by ananace** [comment]
This Flatpak only repackages the [upstream](https://github.com/jitsi/jitsi-meet-electron) appimage - as per their wishes in regards to Linux support.  
As there's currently only x86_64 appimages available, that limits what architectures the Flatpak can support.

I'd suggest opening an issue for ARM/AArch64 builds on the upstream repo.

**Comment by csett86** [comment]
Upstream here: Based on this suggestion I just shipped the arm64 release: https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2023.7.2

**Comment by csett86** [comment]
This seems the way to go to provide both x64_64 and arm64: https://discourse.flathub.org/t/how-to-provide-binaries-for-both-aarch64-arm64-and-x86-64-regular-64-bit/3521

I'll create a PR later this evening to give it a try
