### ISSUE TITLE
All CI-Builds seem to fail

### ISSUE THREAD

**Issue by horas13** [flathub/org.jitsi.jitsi-meet#83]
see https://github.com/flathub/org.jitsi.jitsi-meet/commit/877449002f29bfda8156b1e97d378653df2d7159 and https://github.com/flathub/org.jitsi.jitsi-meet/pull/81 and

**Comment by ananace** [comment]
My assumption is that the flatpak manifest linter has changed its output and the Flathub buildbot doesn't quite understand it when there are warnings anymore.

Guess this is as good a time as any to switch to Wayland by default when on Wayland.
